### PR TITLE
Choose std.debug.print in test mode

### PR DESCRIPTION
**Pull request by mnemnion**
This patch changes `pretty.print` to use `std.debug.print` when in test mode, to avoid whatever race condition with the progress bar was making the 0.12 version hang under those conditions.

Also adds `.zig-*` to .gitignore, to handle the new dotted name for the cache directory.

A potential close for #9.

### CODE REVIEW

**Comment by timfayz** [comment]
@mnemnion, looks about right! Unfortunately, I didn't have to time to look at the progress thing. However, could you please explain what's wrong with writing to stdout in test mode? Is it because using Progress does a lot of writes during the tests? Couldn't we just apply some kind of lock, as is usually done but for stderr:

```zig
    const stderr = std.io.getStdErr().writer();
    var bw = std.io.bufferedWriter(stderr);
    const writer = bw.writer();

    std.debug.lockStdErr();
    defer std.debug.unlockStdErr();
    nosuspend {
        writer.print(...);
        bw.flush();
    }
```

**Comment by mnemnion** [comment]
> However, could you please explain what's wrong with writing to stdout in test mode?

This patch is a pure workaround, I didn't actually figure out what causes the hang in test mode. It also switches the output from `stdout` to `stderr`, which is what `std.debug.print` uses, which is maybe not ideal.   It might make more sense to add a testing-specific print method, although this has the advantage that if a `pretty.print` in ordinary code is invoked by a test, that won't trigger the hang.

That said, using `std.debug.print` is a slightly roundabout way of calling `lockStdErr`, and it doesn't appear than an equivalent `lockStdOut` function exists. 

On a functional level, what's wrong with calling `pretty.print` in test mode (I don't know to what degree that generalizes to all writes to `stdout`) is that the test hangs indefinitely.  I don't know why that's the case. I've been reading some of the code involved, and my hunch is that there's some sort of deadlock arising from resource contention, but I haven't spotted the smoking gun. The progress bar itself is written to stderr, so whatever the problem is, it isn't an obvious one.

**Comment by mnemnion** [comment]
So it turns out this is [a known bug](https://github.com/ziglang/zig/issues/15091) which I didn't happen to hit because the project I use `pretty` in was started on Zig `0.11`.  

So, your call: I think diverting to `stderr` is a reasonable shim until a fix is in, but if that doesn't suit you for whatever reason, I can work around it just as easily in my own code.

Edit: the reason it was working originally might actually be the difference between `zig test` and `zig build test`, I don't know if that's entirely relevant but it pays to be accurate.

**Comment by timfayz** [comment]
Got it. Thank you!

> if that doesn't suit you ...

No, it suits me. I'm just asking because I didn't understand the reason behind this decision. Besides, I'm not much of an expert in Zig or in systems programming in general. pretty is essentially my first project written in a systems language. So considering me as a newbie is a safe way to go.

Am I right that the essence of this change is to use stderr instead of stdout in test mode because the testing framework hangs while parsing something directly from stdout, as you mentioned in the [thread](https://github.com/ziglang/zig/issues/15091)?

By the way, you made a wonderful comment there. You really hit the nail 👍

**Comment by timfayz** [comment]
By the way, the PR solves #9 (at least temporarily). Shouldn't you have mentioned it in the commit message?

**Comment by mnemnion** [comment]
> By the way, the PR solves https://github.com/timfayz/pretty/issues/9 (at least temporarily). Shouldn't you have mentioned it in the commit message?

I had thought mentioning it in the first comment would trigger all the automation stuff. ¯\\\_(ツ)_/¯

**Pull request merged**
