### PR TITLE
U21 print bugfix

### PR DESCRIPTION
**Pull request by mnemnion**
To my chagrin, I didn't consider that other single codepoints which one wouldn't generally consider "printable" are printed directly by my last patch.

This patch correct that, using `\u` escapes for values which can't appear in Zig source code without being encoded, as well as C1 codes, which are currently accepted by the parser (I think this is just an oversight).

### CODE REVIEW

**Comment by timfayz** [comment]
Great! Though too busy to review. @mnemnion, could you please give some resources to read more about those char ranges? Not sure where do they come from:
```zig
                        switch (val) {
                            // Some characters we want/need to escape:
                            // C0/C1 controls and surrogate codepoints
                            0x01...0x08,
                            0x0b...0x0c,
                            0x0e,
                            0x0f,
                            => {
                                try s.appendValFmt("'\\u{{0{x}}}'", val, c);
                            },
                            0x09 => try s.appendVal("'\\t'", c),
                            0x0a => try s.appendVal("'\\n'", c),
                            0x0d => try s.appendVal("'\\r'", c),
                            0x10...0x1f,
                            0x7f...0x92,
                            0xd800...0xdfff,
                            => {
                                try s.appendValFmt("'\\u{{{x}}}'", val, c);
                            },
                            else => try s.appendValFmt("'{u}'", val, c),
```
Also, if I am not mistaken, we need to lowercase `zig.builtin.Type` tags to reflect latest Zig changes:
```zig
+                .int => |int| {
-                .Int => |int| {
                    if (opt.u21_is_codepoint and int.bits == 21 and int.signedness == .unsigned) {
```

**Comment by mnemnion** [comment]
Yes, my understanding is that it will be necessary to lowercase all Type enum values for `0.14`.   I don't know how you want to approach backward compatibility there, if you even do.   I'd like for `ohsnap` to support `0.13` until `0.15` comes around, but on my end that can be accomplished by including whatever the last `pretty` version is to use the old style, as well as the latest version, and conditionally including one or the other based on version information in `builtin`. 

The values, commented: 

```zig 
switch (val) {
    // Some characters we want/need to escape:
    // C0/C1 controls and surrogate codepoints

    // C0 controls (illegal, not generally thought of as printable
    0x01...0x08,
    0x0b...0x0c,
    0x0e,
    0x0f,
    => {
        try s.appendValFmt("'\\u{{0{x}}}'", val, c);
    },
    // C0s which are escaped as such in Zig 
    0x09 => try s.appendVal("'\\t'", c),
    0x0a => try s.appendVal("'\\n'", c),
    0x0d => try s.appendVal("'\\r'", c),
    // Remaining C0s
    0x10...0x1f,
    // Backspace (0x74) and C1 control codes,
    // Also not printable (although C1s are currently
    // legal to embed in Zig strings, they probably should not be)
    0x7f...0x92,
    // Surrogate codepoints, invalid to encode in UTF-8
    0xd800...0xdfff,
    => {
        try s.appendValFmt("'\\u{{{x}}}'", val, c);
    },
    // Everything else. Includes too-high codepoints, which
    // the {u} format replaces with the Unicode Replacement
    // character U+FFFD (�)
    else => try s.appendValFmt("'{u}'", val, c),
```
I picked these based on a) I know a lot about Unicode and b) spent some time looking through the Zig parser to see how it handles validity of multi-line strings.  `'\t'`, `'\n'`, `'\r'` are encoded as such because it would look strange to leave them as raw characters, and those escape sequences are more conventional than e.g. `'\u{09}'`, although that form is valid Zig. 

All of the `\u` encoded characters are illegal to embed in a Zig string, except for the C1s. Which shouldn't actually be allowed because, among other reasons, you can create terminal escape sequences with them. 

I considered using `\x` escaping for the C0 and for backslash, it seems incrementally more idiomatic, but it's also an unnecessary inconsistency.  Would be easy to change if you think the other way is nicer, it was basically a toss-up for me.

**Comment by timfayz** [comment]
> Yes, my understanding is that it will be necessary to lowercase all Type enum values for 0.14. I don't know how you want to approach backward compatibility there, if you even do.

Yes, I didn't think about backwards compatibility. I simply assumed it will be achieved through versions (ie. if you want 0.13 compatible, download the previous version and that's about it). But since it is important to you, we can do the following:
- Keep `main` branch "cutting edge" and compatible with the latest zig.
- Create `0.13.0-compat-latest` branch that starts from this merge. As soon as `main` updates, pull changes back onto this branch.

I'm not a git expert, so if you have better ideas feel free to share.

Regarding the byte ranges. The first C0 part is super clear (and I could have guessed it myself in the first place lol):
```zig
    0x01...0x08,
    0x0b...0x0c,
    0x0e,
    0x0f,
    => {
        try s.appendValFmt("'\\u{{0{x}}}'", val, c);
    },
    0x09 => try s.appendVal("'\\t'", c),
    0x0a => try s.appendVal("'\\n'", c),
    0x0d => try s.appendVal("'\\r'", c),
    // Remaining C0s
    0x10...0x1f,
```

Then goes something suspicious:
```zig
    // Backspace (0x74) and C1 control codes,
    // Also not printable (although C1s are currently
    // legal to embed in Zig strings, they probably should not be)
    0x7f...0x92,
```
1. I guess instead of "Backspace" and `0x74` (corresponds to `t`)  you meant `DEL` that starts at `7f`, which is exactly the beginning of the range the comment at. 
2. The end of range is `0x92`. Why isn't it `0x9f`? According to https://en.wikipedia.org/wiki/C0_and_C1_control_codes and especially https://www.utf8-chartable.de/, the C1 range ends at `9f`.

**Comment by timfayz** [comment]
> The last part:
> ```zig
>     // Surrogate codepoints, invalid to encode in UTF-8
>     0xd800...0xdfff,
> ```
> I don't think at this range code points directly correspond to...

**Update**: The last part is clear now. I had confused that we interpret the value as a _codepoint_, not its representation. After you comment on my previous reply, we are good to merge.

**Comment by mnemnion** [comment]
> I guess instead of "Backspace" and 0x74 (corresponds to t) you meant DEL that starts at 7f, which is exactly the beginning of the range the comment at.

Yes, this is correct. They are [frequently switched](https://en.wikipedia.org/wiki/Backspace#Common_use), which makes it easy to confuse. We want to escape both delete and backspace, of course. 

I've been working on a terminal input parser which has a quirks table, one of which is `.backspace_as_delete`, which scrambled things a bit. `0x74` was just a typo. 

> The end of range is 0x92. Why isn't it 0x9f? According to https://en.wikipedia.org/wiki/C0_and_C1_control_codes and especially https://www.utf8-chartable.de/, the C1 range ends at 9f.

Good catch! A typo as well, much like 74 instead of 7f, but this time in the code, where it affects the function. I've been known to typo entire words, for the record. I've pushed the change.

Would you like the documentation in the switch statement as well? It would be easy to add, I only added it here in the issue thread.

**Comment by timfayz** [comment]
> Would you like the documentation in the switch statement as well?

Update: Never mind, I started doing it myself, including the refactor of tests you added.

**Comment by timfayz** [comment]
@mnemnion I'm new to working with PRs and I have a question. Why the PR was simply closed? I was hoping the status will be "merged". I did a manual `--squash` merge referencing PR's id:
```
git fetch origin pull/13/head:pr-13
git merge --squash -X theirs pr-13
git commit
```
I did squash instead of ` git merge --no-ff` because when I do the latter, git log/history becomes super messy to the point where I can't even recognize where I actually am myself. Is it ok with you I did a squash, or do you prefer keeping the history of your commits in the merge?

**Comment by mnemnion** [comment]
I'm not concerned about the history/credit/whatever. It's your project, I've got a contrib badge already, all is well. ^_^ 

I wish I could answer your question but the interaction between GitHub and git is pretty mysterious to me. I feel like I understand each of those reasonably well in isolation, but strange things happen whenever I go off the beaten path of PR workflows. 

I realize I never answered your question about 0.13 / 0.14. For my purposes, just making a release tarball right before you make the changes will work fine. If there's some relevant change after that, I'll backport it on a fork branch.

**Pull request closed without merging**
